PdfServ/PdfServ/Models/PDFHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Drawing.Printing;
using TuesPechkin;
using System.IO;

namespace PdfServ.Models
{
    public class PDFHelper
    {
        public static string DLL_PATH = HttpContext.Current.Server.MapPath("~") + "\\bin\\TuesPechkin.Wkhtmltox.Win32.dll";

        public enum DataType
        {
            HTML,
            URL
        }

        /*
        private static IConverter converter =
            new ThreadSafeConverter(
                new RemotingToolset<PdfToolset>(
                    new Win32EmbeddedDeployment(
                        new TempFolderDeployment())));
        */

        private static IDeployment deployment =
                new Win32EmbeddedDeployment(new TempFolderDeployment());

        private static IConverter converter =
            new ThreadSafeConverter(
                new PdfToolset(deployment));

        public static byte[] ConvertToPdf(PDFHelper.DataType type, string data, string documentName)
        {
            var webSettings = new WebSettings
            {
                EnableJavascript = true,
                LoadImages = true,
                EnableIntelligentShrinking = true
            };

            ObjectSettings objSettings = null;

            if (type == DataType.HTML)
                objSettings = new ObjectSettings { HtmlText = data, WebSettings = webSettings };
            else
                objSettings = new ObjectSettings { PageUrl = data, WebSettings = webSettings };

            var document = new HtmlToPdfDocument
            {
                GlobalSettings =
                {
                    ProduceOutline = true,
                    DocumentTitle = documentName,
                    PaperSize = PaperKind.Letter,
                    UseCompression = true,
                    ImageDPI = 600,
                    ImageQuality = 100,
                    

                    //DPI = 1200,
                    Margins =
                    {
                        Top = 1,
                        Right = 0.5,
                        Bottom = 1,
                        Left = 0.5,
                        Unit = Unit.Centimeters
                    }
                },
                Objects = {
                   objSettings
                }
            };

            // Keep the converter somewhere static, or as a singleton instance!

            byte[] result = converter.Convert(document);

            return result;
        }
    }
}

PdfServ/PdfServ/Controllers/PdfController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Text;
using System.Drawing.Printing;

using TuesPechkin;
using PdfServ.Models;

namespace PdfServ.Controllers
{
    public class PdfController : Controller
    {

        public static string DEFAULT_URL = "https://en.wikipedia.org/";
        public static string DEFAULT_DOCNAME = "My Document";
        public static string DEFAULT_FILENAME = "my_pdf.pdf";
        enum DataType {
            HTML,
            URL
        }

        // GET: Pdf
        public ActionResult Index()
        {
            ViewBag.defaultUrl = DEFAULT_URL;
            ViewBag.defaultDocName = DEFAULT_DOCNAME;
            ViewBag.defaultFileName = DEFAULT_FILENAME;
            return View();
        }

        // GET: PDF
        [HttpGet, ValidateInput(false)]
        public ActionResult Get()
        {
            return ProcessRequest();
        }

        // POST: PDF
        [HttpPost, ValidateInput(false)]
        public ActionResult Download()
        {
            return ProcessRequest();
        }

        public ActionResult ProcessRequest()
        {
            var url = Request["url"];
            var html = Request["html"];

            var documentName = Request["docName"];
            if (string.IsNullOrEmpty(documentName))
            {
                documentName = DEFAULT_DOCNAME;
            }

            var fileName = Request["fileName"];
            if (string.IsNullOrEmpty(fileName))
            {
                fileName = DEFAULT_FILENAME;
            }

            byte[] pdfBuf = null;

            if (!string.IsNullOrEmpty(html))
            {
                pdfBuf = PDFHelper.ConvertToPdf(PDFHelper.DataType.HTML, html, documentName);
            }
            else
            {
                if (string.IsNullOrEmpty(url))
                    url = DEFAULT_URL;

                pdfBuf = PDFHelper.ConvertToPdf(PDFHelper.DataType.URL, url, documentName);
            }

            if (pdfBuf == null)
            {
                // return error here.
            }

            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = fileName,

                // always prompt the user for downloading, set to true if you want 
                // the browser to try to show the file inline
                Inline = false,
            };

            Response.AppendHeader("Content-Disposition", cd.ToString());
            return File(pdfBuf, "application/pdf");
        }
    }
}

PdfServ/PdfServ/Views/Pdf/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<br />

<p>
    About the project: 
</p>
<ul>
    <li>wkhtmltopdf it's the used library and it's based on webkit <a href="http://wkhtmltopdf.org/">http://wkhtmltopdf.org/</a></li>
    <li>We are using a .net wrapper from wkhtmltopdf and you can install this package using the nuget pachage manager: <a href="https://www.nuget.org/packages/TuesPechkin/">TuesPechkin 1.0.3</a></li>
    <li><a href="https://github.com/tuespetre/TuesPechkin">Original library -> https://github.com/tuespetre/TuesPechkin</a></li>
    <li><a href="http://wkhtmltopdf.org/usage/wkhtmltopdf.txt">how to use wkhtmltopdf</a></li>
</ul>

<p>
    Know issues and solutions:
</p>
<ul>
    <li>Gif images are not supported!. No solutions for this for now!.</li>
    <li>You must compile your project as x86</li>
    <li>The application pool should have the flag "Enable 32-Bit Applications = True"</li>
    <li>Images under HTTPS are not rendered inside the PDF. Solution: Download and install OpenSSL on the server (More details here: http://www.openssl.org/related/binaries.html)</li>
    <li>Get example @Html.ActionLink("https://en.wikipedia.org/", "Get", new { url = "https://en.wikipedia.org/" })</li>
</ul>

<h1>Test the library!!!</h1>

@using (Html.BeginForm("Download", "Pdf", FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
{
    <div class="form-group">
        <label for="docName" class="col-sm-2 control-label">Document Name: </label>
        <div class="col-sm-10">
            <input type="text" name="docName" id="docName" class="form-control" value="" placeholder="@ViewBag.defaultDocName" />
        </div>
    </div>
    <div class="form-group">
        <label for="url" class="col-sm-2 control-label">Url: </label>
        <div class="col-sm-10">
            <input type="text" name="url" id="url" class="form-control" value="" placeholder="@ViewBag.defaultUrl" />
        </div>
    </div>
    <div class="form-group">
        <label for="html" class="col-sm-2 control-label">HTML: </label>
        <div class="col-sm-10">
            <textarea rows="4" cols="40" class="form-control" name="html" id="html"></textarea>
        </div>
    </div>
    <div class="form-group">
        <label for="fileName" class="col-sm-2 control-label">File Name:</label>
        <div class="col-sm-10">
            <input type="text" name="fileName" id="fileName" value="" placeholder="@ViewBag.defaultFileName" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Convert to PDF</button>
        </div>
    </div>
}

PdfServ/PdfServ/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PDF Generator Service</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <meta name="description" content="The description of my page" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PDF Generator Service", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PDF Generator Service</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>